#!/bin/bash
yum -y install gcc pcre-devel  zlib-devel openssl-devel
yum -y install php php-fpm php-mysql mariadb-devel mariadb-server mariadb 
useradd -s /sbin/nologin nginx
wget ftp://192.168.4.254/lnmp_soft/nginx-1.12.2.tar.gz
tar -xf nginx-1.12.2.tar.gz
cd nginx-1.12.2/
./configure --user=nginx --group=nginx --with-stream --with-http_ssl_module --with-http_stub_status_module
make &&  make install
ln -s /usr/local/nginx/sbin/nginx /sbin/
sed -i '65,68s/^ *#//g' /usr/local/nginx/conf/nginx.conf
sed -i '70,71s/^ *#//g' /usr/local/nginx/conf/nginx.conf
sed -i 70s/fastcgi_params/fastcgi.conf/ /usr/local/nginx/conf/nginx.conf
systemctl start php-fpm
systemctl enable php-fpm 
systemctl start mariadb
systemctl enable mariadb./
